name: Build

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/powertoys-run-build.yml@main
    strategy:
      matrix:
        platform:
          - x64
    with:
      dotnet-version: "9.0.x"
      plugin-name: "CountrySearch"
      platform: ${{ matrix.platform }}
      solution-path: "PowerToys-Run-CountrySearch.sln"
      project-path: "Community.PowerToys.Run.Plugin.CountrySearch"
