name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  publish:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/powertoys-run-publish.yml@main
    strategy:
      matrix:
        platform:
          - x64
          - ARM64
    with:
      dotnet-version: "8.0.x"
      plugin-name: "CountrySearch"
      platform: ${{ matrix.platform }}
      solution-path: "PowerToys-Run-CountrySearch.sln"
      project-path: "Community.PowerToys.Run.Plugin.CountrySearch"
